# Generated by Django 5.2 on 2025-04-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="posts",
            field=models.ManyToManyField(related_name="categories", to="main.post"),
        ),
        migrations.DeleteModel(
            name="PostOnCategorys",
        ),
    ]
