# Generated by Django 5.2 on 2025-04-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_category_posts_delete_postoncategorys"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(related_name="posts", to="main.category"),
        ),
    ]
