# Generated by Django 5.2 on 2025-04-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_category_posts_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Python for beginners", max_length=200),
            preserve_default=False,
        ),
    ]
